services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: ai-chat:latest
    container_name: ai-chat
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "7475:7475"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 128M
        reservations:
          cpus: "0.05"
          memory: 32M
